sudo:  required
services:
  - docker

before_install:
  - docker build -t harryspooner/dockdemo -f Dockerfile.dev .

script:
  - docker run -e CI=true harryspooner/dockdemo npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-646987636463"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_AK
  secret_access_key: 
    secure: "$AWS_SK"
