sudo:  required
services:
  - docker

before_install:
  - docker build -t harryspooner/dockdemo -f Dockerfile.dev .

script:
  - docker run -e CI=true harryspooner/dockdemo npm run test -- --coverage
